# Generated by Django 3.2.6 on 2021-08-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=200)),
                ('customer_father_name', models.TextField(max_length=200)),
                ('customer_profile', models.TextField(max_length=200)),
                ('loan_amount_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanAmountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggrement_data', models.DateField()),
                ('lrn', models.TextField(max_length=200)),
                ('tenor', models.TextField(max_length=200)),
                ('adv_emi', models.TextField(max_length=200)),
                ('mob', models.TextField(max_length=200)),
                ('customer_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOfficeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_pincode', models.TextField(max_length=200)),
                ('office_landmark', models.TextField(max_length=200)),
                ('office_address1', models.TextField(max_length=200)),
                ('office_address2', models.TextField(max_length=200)),
                ('office_address3', models.TextField(max_length=200)),
                ('customer_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHomeAddressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.TextField(max_length=200)),
                ('landmark', models.TextField(max_length=200)),
                ('address1', models.TextField(max_length=200)),
                ('address2', models.TextField(max_length=200)),
                ('address3', models.TextField(max_length=200)),
                ('customer_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='BranchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.TextField(max_length=200)),
                ('region_name', models.TextField(max_length=200)),
                ('area_name', models.TextField(max_length=200)),
                ('branch_name', models.TextField(max_length=200)),
                ('branch_code', models.TextField(max_length=200)),
                ('customer_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customermodel')),
            ],
        ),
    ]
