# Generated by Django 3.2.6 on 2021-08-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_customermodel_customerdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchdata',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerhomeaddressdata',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerofficedata',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='loanamountdata',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
